.PHONY: test

test:
	@echo "-----------------------"
	@echo "| Advent of Code 2025 |"
	@echo "-----------------------"
	@make -C day-01
	@make -C day-02
	@make -C day-03
	@make -C day-04
	@make -C day-05
	@make -C day-06
	@make -C day-07
	@make -C day-08
	@make -C day-09
	@make -C day-10
	@make -C day-11
	@make -C day-12
