name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5.0.0

      - name: Check Formatting
        run: make format && git diff --exit-code HEAD

      - name: Build Project
        run: make --no-print-directory
